### PR TITLE
Issue #5 memory manager redesign

### PR DESCRIPTION
**Pull request by holzkohlengrill**
Description tacked in #5

### CODE REVIEW

**Comment by holzkohlengrill** [comment]
https://github.com/bmwcarit/Emma/tree/ISSUE_%235_MemoryManagerRedesign/tests/other_files

iIs not longer needed. Please remove (@KGergo88 ).

**Comment by KGergo88** [comment]
> https://github.com/bmwcarit/Emma/tree/ISSUE_%235_MemoryManagerRedesign/tests/other_files
> 
> iIs not longer needed. Please remove (@KGergo88 ).

Since the CI tools only generate such results for the master, it is indeed needed.

**Comment by holzkohlengrill** [comment]
> > https://github.com/bmwcarit/Emma/tree/ISSUE_%235_MemoryManagerRedesign/tests/other_files
> > iIs not longer needed. Please remove (@KGergo88 ).
> 
> Since the CI tools only generate such results for the master, it is indeed needed.

Therefore you can create a pull request and see the results.

**Comment by KGergo88** [comment]
> > > https://github.com/bmwcarit/Emma/tree/ISSUE_%235_MemoryManagerRedesign/tests/other_files
> > > iIs not longer needed. Please remove (@KGergo88 ).
> > 
> > 
> > Since the CI tools only generate such results for the master, it is indeed needed.
> 
> Therefore you can create a pull request and see the results.

I would prefer to keep this script.

**Comment by KGergo88** [comment]
> Drive `c` on linux will probably not work :-)
> Can't this be done with relative paths?

Fixed in: 1c845d0

**Comment by KGergo88** [comment]
@holzkohlengrill The remaining 6 Codacy issues are only the subprocess calls in genDoc. I will not waste time on solving them. Please try to ignore them in Codacy somehow.

**Comment by KGergo88** [comment]
@holzkohlengrill The code duplications in the unit tests are also worth the time to investigate them. Some of them are also false positives. Please ignore the "tests" folder regarding duplications.

**Comment by KGergo88** [comment]
@holzkohlengrill The Travis build is failing because of the issue #11. See unit test "test_noMemStats". Please implement a solution for this issue.

**Review by holzkohlengrill — COMMENTED** [review]
**Don't directly include new dependencies without my consent!**

https://github.com/bmwcarit/Emma/pull/10/files/e73b0f32ee3d3547bea24f0eba8dd36adee3c10d..38a3be146a2989cb5164f28f32d4573026205ffe#diff-f8d35c1391668fdee003239819a70f6d

-> The folder `test/other_files` should not exist anyway.

**Comment by KGergo88** [comment]
@holzkohlengrill: All points were implemented. Can I merge into master?

**Review by KGergo88 — APPROVED** [review]

**Pull request merged**
